name: Deploy to seohost

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: h96.seohost.pl
          username: srv104971
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./meritoros-theme/
          server-dir: /public_html/wp-content/themes/meritoros-theme/
